'use client';
import Image from 'next/image';
import Link from 'next/link';
import { Check, Clock3, Flame, Star, Trash2, Dumbbell } from 'lucide-react';
import { useState } from 'react';
import toast from 'react-hot-toast';
import { useApp } from '../components/AppProvider';

function PlanCard({ workout, done, onDone, onRemove }) { return <div className={`rounded-2xl border border-white/10 bg-[var(--panel)] p-4 ${done?'opacity-60':''}`}><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><div className="relative h-24 w-full overflow-hidden rounded-xl bg-[#1a1a1a] sm:w-32 sm:shrink-0"><Image src={workout.image} alt={workout.name} fill sizes="128px" className="object-cover"/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2">{workout.muscleGroups.map(g=><span key={g} className="text-[9px] font-black uppercase tracking-widest text-[var(--accent)]">{g}</span>)}</div><h3 className="display mt-1 text-2xl uppercase">{workout.name}</h3><p className="mt-1 text-xs text-white/35">{workout.equipment}</p><div className="mt-3 flex flex-wrap gap-4 text-xs text-white/45"><span className="flex gap-1"><Clock3 size={14}/> {workout.duration} min</span><span className="flex gap-1"><Flame size={14}/> {workout.caloriesBurned} kcal</span><span className="flex gap-1"><Star size={14}/> {workout.rating}</span></div></div><div className="flex flex-wrap gap-2 sm:flex-col"><Link href={`/workout/${workout.id}`} className="rounded-lg border border-white/10 px-3 py-2 text-[10px] font-black uppercase tracking-wider text-center">View Details</Link><button onClick={onDone} className={`rounded-lg px-3 py-2 text-[10px] font-black uppercase tracking-wider ${done?'bg-white/10 text-white/60':'bg-[var(--accent)] text-black'}`}>{done?'Done':'Mark as Done'}</button><button onClick={onRemove} className="grid h-9 w-9 place-items-center rounded-lg border border-red-400/20 text-red-300 hover:bg-red-400/10" aria-label="Remove"><Trash2 size={15}/></button></div></div></div> }

export default function MyPlan(){ const {plan,saved,done,toggleDone,removeFromPlan,removeSaved}=useApp(); const [tab,setTab]=useState('plan'); const items=tab==='plan'?plan:saved; const minutes=plan.reduce((a,w)=>a+w.duration,0), calories=plan.reduce((a,w)=>a+w.caloriesBurned,0); const remove=()=>{removeFromPlan;}; return <div className="container py-12 sm:py-16"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[.2em] text-[var(--accent)]">Your daily log</p><h1 className="display mt-3 text-6xl uppercase sm:text-7xl">My Plan</h1><p className="mt-4 text-sm leading-6 text-white/45">Cap of five lifts for today. Finish them, then load more.</p></div><div className="mt-10 grid gap-3 sm:grid-cols-3">{[['Exercises',plan.length],['Minutes',minutes],['Calories',calories]].map(([l,v])=><div key={l} className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><p className="text-[10px] font-black uppercase tracking-[.18em] text-white/35">{l}</p><p className="display mt-2 text-4xl">{v}</p></div>)}</div><div className="mt-10 flex gap-2 border-b border-white/10"><button onClick={()=>setTab('plan')} className={`px-4 py-4 text-xs font-black uppercase tracking-[.15em] ${tab==='plan'?'border-b-2 border-[var(--accent)] text-[var(--accent)]':'text-white/40'}`}>Today&apos;s Plan ({plan.length})</button><button onClick={()=>setTab('saved')} className={`px-4 py-4 text-xs font-black uppercase tracking-[.15em] ${tab==='saved'?'border-b-2 border-[var(--accent)] text-[var(--accent)]':'text-white/40'}`}>Saved ({saved.length})</button></div><div className="mt-6 space-y-4">{items.length===0?<div className="rounded-3xl border border-dashed border-white/15 px-5 py-20 text-center"><Dumbbell className="mx-auto text-white/25"/><h2 className="display mt-5 text-3xl uppercase">Nothing Here Yet</h2><p className="mx-auto mt-3 max-w-md text-sm text-white/40">Browse the library and add a lift to get today moving.</p><Link href="/" className="mt-6 inline-flex rounded-full bg-[var(--accent)] px-5 py-3 text-xs font-black uppercase text-black">Go to workouts</Link></div>:items.map(w=><PlanCard key={w.id} workout={w} done={done.includes(w.id)} onDone={()=>{toggleDone(w.id);toast.success(done.includes(w.id)?'Marked as active':'Workout marked as done')}} onRemove={()=>{tab==='plan'?removeFromPlan(w.id):removeSaved(w.id);toast.success(tab==='plan'?'Removed from today\'s plan':'Removed from saved')}}/>)}</div></div> }
